import osimport httpxfrom datetime import datetime, timedeltafrom typing import List, Literal, Optional, Dict, Any
from fastapi import FastAPI, HTTPException, statusfrom fastapi.middleware.cors import CORSMiddlewarefrom pydantic import BaseModel, Fieldfrom openai import OpenAI
# ---------------------------------------------------------------------------# App Initialization & CORS# ---------------------------------------------------------------------------app = FastAPI(title="Milo All-in-One Personal AI Assistant Engine")
app.add_middleware(    CORSMiddleware,    allow_origins=["*"],    allow_credentials=True,    allow_methods=["*"],    allow_headers=["*"],)
openai_client = OpenAI(api_key=os.getenv("OPENAI_API_KEY"))
# Environment VariablesTWILIO_ACCOUNT_SID = os.getenv("TWILIO_ACCOUNT_SID")TWILIO_AUTH_TOKEN = os.getenv("TWILIO_AUTH_TOKEN")TWILIO_WHATSAPP_NUMBER = os.getenv("TWILIO_WHATSAPP_NUMBER", "whatsapp:+14155238886")
# In-Memory Storage for Reminders, Notes, and Calendar itemsREMINDERS_DB: List[Dict[str, Any]] = []NOTES_DB: List[Dict[str, Any]] = []
# ---------------------------------------------------------------------------# Data Models / Schemas# ---------------------------------------------------------------------------
# 1. Email Modelsclass EmailDraftRequest(BaseModel):    context_or_email: str    recipient: Optional[str] = None    style: Literal["professional", "casual", "brief"] = "professional"
class EmailDraftResponse(BaseModel):    subject: str    body: str
class SendEmailPayload(BaseModel):    provider: Literal["gmail", "outlook"]    access_token: str    recipient_email: str    subject: str    body: str
# 2. Calendar & Reminder Modelsclass CalendarEventPayload(BaseModel):    provider: Literal["google", "outlook"]    access_token: str    title: str    description: Optional[str] = ""    start_iso: str    end_iso: str
class ReminderCreatePayload(BaseModel):    text: str    due_datetime: str # ISO format string: YYYY-MM-DDTHH:MM:SS    send_whatsapp: bool = False    phone_number: Optional[str] = None
# 3. Notes Modelsclass NoteItem(BaseModel):    raw_content: str
class CleanNoteResponse(BaseModel):    title: str    key_points: List[str]    action_items: List[str]    cleaned_note: str
# 4. Social Media & Chat Modelsclass ChatPrompt(BaseModel):    message: str
class SocialDraftRequest(BaseModel):    platform: Literal["instagram", "linkedin"]    topic_or_idea: str    target_audience: Optional[str] = "General"
class InstagramDraft(BaseModel):    caption: str    hook: str    carousel_slides: List[str]    hashtags: List[str]
class LinkedInDraft(BaseModel):    hook: str    body: str    call_to_action: str    hashtags: List[str]
# ---------------------------------------------------------------------------# 1. EMAIL MANAGER (Gmail, Outlook & AI Drafting)# ---------------------------------------------------------------------------
@app.post("/api/email/draft", response_model=EmailDraftResponse)async def draft_email(req: EmailDraftRequest):    """Generates an email draft or reply in the requested tone."""    system_prompt = (        f"You are Milo, an executive communication assistant. "        f"Draft a response or new email matching the style: '{req.style}'. "        f"Output a concise subject line and clean email body."    )        response = openai_client.beta.chat.completions.parse(        model="gpt-4o-mini",        messages=[            {"role": "system", "content": system_prompt},            {"role": "user", "content": f"Context/Input:\n{req.context_or_email}"}        ],        response_format=EmailDraftResponse,    )    return response.choices[0].message.parsed
@app.post("/api/email/send")async def send_email(req: SendEmailPayload):    """Sends an email via Google Gmail API or Microsoft Graph API (Outlook)."""    async with httpx.AsyncClient() as client:        if req.provider == "gmail":            import base64            from email.mime.text import MIMEText
            message = MIMEText(req.body)            message["to"] = req.recipient_email            message["subject"] = req.subject            raw_message = base64.urlsafe_b64encode(message.as_bytes()).decode()
            res = await client.post(                "https://gmail.googleapis.com/gmail/v1/users/me/messages/send",                headers={"Authorization": f"Bearer {req.access_token}"},                json={"raw": raw_message},            )            if res.status_code >= 400:                raise HTTPException(status_code=res.status_code, detail=res.text)            return {"status": "sent", "provider": "gmail", "response": res.json()}
        elif req.provider == "outlook":            outlook_payload = {                "message": {                    "subject": req.subject,                    "body": {"contentType": "Text", "content": req.body},                    "toRecipients": [{"emailAddress": {"address": req.recipient_email}}],                }            }            res = await client.post(                "https://graph.microsoft.com/v1.0/me/sendMail",                headers={                    "Authorization": f"Bearer {req.access_token}",                    "Content-Type": "application/json",                },                json=outlook_payload,            )            if res.status_code >= 400:                raise HTTPException(status_code=res.status_code, detail=res.text)            return {"status": "sent", "provider": "outlook"}
# ---------------------------------------------------------------------------# 2. CALENDAR & REMINDERS (Google, Outlook, In-App Alarms & WhatsApp)# ---------------------------------------------------------------------------
@app.post("/api/calendar/add-event")async def add_calendar_event(event: CalendarEventPayload):    """Creates a calendar event on Google Calendar or Outlook."""    async with httpx.AsyncClient() as client:        if event.provider == "google":            body = {                "summary": event.title,                "description": event.description,                "start": {"dateTime": event.start_iso},                "end": {"dateTime": event.end_iso},            }            res = await client.post(                "https://www.googleapis.com/calendar/v3/calendars/primary/events",                headers={"Authorization": f"Bearer {event.access_token}"},                json=body,            )            if res.status_code >= 400:                raise HTTPException(status_code=res.status_code, detail=res.text)            return {"status": "created", "provider": "google", "event": res.json()}
        elif event.provider == "outlook":            body = {                "subject": event.title,                "body": {"contentType": "HTML", "content": event.description},                "start": {"dateTime": event.start_iso, "timeZone": "UTC"},                "end": {"dateTime": event.end_iso, "timeZone": "UTC"},            }            res = await client.post(                "https://graph.microsoft.com/v1.0/me/events",                headers={                    "Authorization": f"Bearer {event.access_token}",                    "Content-Type": "application/json",                },                json=body,            )            if res.status_code >= 400:                raise HTTPException(status_code=res.status_code, detail=res.text)            return {"status": "created", "provider": "outlook", "event": res.json()}
@app.post("/api/reminders/create")async def create_reminder(payload: ReminderCreatePayload):    """Creates an alarm/reminder and optionally sends an instant WhatsApp alert."""    reminder = {        "id": len(REMINDERS_DB) + 1,        "text": payload.text,        "due_datetime": payload.due_datetime,        "send_whatsapp": payload.send_whatsapp,        "phone_number": payload.phone_number,        "created_at": datetime.utcnow().isoformat(),    }    REMINDERS_DB.append(reminder)
    # Trigger WhatsApp alert via Twilio if requested    if payload.send_whatsapp and payload.phone_number and TWILIO_ACCOUNT_SID and TWILIO_AUTH_TOKEN:        formatted_to = payload.phone_number if payload.phone_number.startswith("whatsapp:") else f"whatsapp:{payload.phone_number}"        whatsapp_url = f"https://api.twilio.com/2010-04-01/Accounts/{TWILIO_ACCOUNT_SID}/Messages.json"                async with httpx.AsyncClient() as client:            await client.post(                whatsapp_url,                auth=(TWILIO_ACCOUNT_SID, TWILIO_AUTH_TOKEN),                data={                    "From": TWILIO_WHATSAPP_NUMBER,                    "To": formatted_to,                    "Body": f" *Milo Reminder Alarm*\n\n{payload.text}\nDue: {payload.due_datetime}",                },            )
    return {"status": "scheduled", "reminder": reminder}
@app.get("/api/reminders")async def list_reminders():    return {"reminders": REMINDERS_DB}
# ---------------------------------------------------------------------------# 3. QUICK NOTES & BRAIN DUMP ORGANIZER# ---------------------------------------------------------------------------
@app.post("/api/notes/cleanup", response_model=CleanNoteResponse)async def clean_up_notes(note: NoteItem):    """Transforms raw brain dumps into actionable, structured bullet points."""    prompt = f"""    Transform this unorganized raw note into a structured summary:    - Give it a crisp title.    - Extract primary key points.    - Identify direct action items/to-dos.    - Write a clean, polished version of the note.
    Raw Note:    \"\"\"{note.raw_content}\"\"\"    """    cleaned = openai_client.beta.chat.completions.parse(        model="gpt-4o-mini",        messages=[{"role": "user", "content": prompt}],        response_format=CleanNoteResponse,    ).choices[0].message.parsed
    NOTES_DB.append(cleaned.dict())    return cleaned
# ---------------------------------------------------------------------------# 4. SOCIAL MEDIA CREATOR & CHAT STUDIO# ---------------------------------------------------------------------------
@app.post("/api/social/instagram", response_model=InstagramDraft)async def generate_instagram_post(req: SocialDraftRequest):    """Generates an aesthetic Instagram post, carousel outline, and hashtag set."""    prompt = f"Create an engaging Instagram post about: {req.topic_or_idea}. Target audience: {req.target_audience}."    return openai_client.beta.chat.completions.parse(        model="gpt-4o-mini",        messages=[{"role": "user", "content": prompt}],        response_format=InstagramDraft,    ).choices[0].message.parsed
@app.post("/api/social/linkedin", response_model=LinkedInDraft)async def generate_linkedin_post(req: SocialDraftRequest):    """Generates a high-engagement LinkedIn post with strong hooks and formatting."""    prompt = f"Write a professional LinkedIn thought-leadership post about: {req.topic_or_idea}. Target audience: {req.target_audience}."    return openai_client.beta.chat.completions.parse(        model="gpt-4o-mini",        messages=[{"role": "user", "content": prompt}],        response_format=LinkedInDraft,    ).choices[0].message.parsed
@app.post("/api/chat")async def assistant_chat(prompt: ChatPrompt):    """Interactive conversational chat endpoint for Milo."""    response = openai_client.chat.completions.create(        model="gpt-4o-mini",        messages=[            {"role": "system", "content": "You are Milo, a smart, proactive personal AI assistant helping with work, daily life, organization, and business."},            {"role": "user", "content": prompt.message}        ]    )    return {"reply": response.choices[0].message.content}
# ---------------------------------------------------------------------------# Local Runner# ---------------------------------------------------------------------------if __name__ == "__main__":    import uvicorn    uvicorn.run(app, host="0.0.0.0", port=8000)
